# A sample Gemfile
source "https://rubygems.org"
ruby "2.2.0"

gem "sinatra"
gem "wombat"
gem "resque", "~> 2.0.0.pre.1", github: "resque/resque"
gem "redis"
gem "bson_ext"
gem "shotgun"
gem "mongoid", "~> 4.0.0"
gem "rspec"
gem "guard"
gem 'guard-rspec', require: false
gem 'domainator'